---
apiVersion: v1
kind: Secret
metadata:
  name: ainek2-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-ms/ainek2-frontend-gitops
